<?xml version="1.0" encoding="utf-8"?><Database Name="NGO_Website" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-8JPNURT;Initial Catalog=NGO_Website;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NGO_WebsiteConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CharityFund" Member="CharityFunds">
    <Type Name="CharityFund">
      <Column Name="FundId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FundName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CommunityDonate" Member="CommunityDonates">
    <Type Name="CommunityDonate">
      <Column Name="CommunityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CommunityName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Donor" Member="Donors">
    <Type Name="Donor">
      <Column Name="DonorId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ToTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonorName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Event" Member="Events">
    <Type Name="Event">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DesiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Local" Member="Locals">
    <Type Name="Local">
      <Column Name="LocalId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LocalCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Manager" Member="Managers">
    <Type Name="Manager">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ManagerCommunity" Member="ManagerCommunities">
    <Type Name="ManagerCommunity">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommunityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ManagerEvent" Member="ManagerEvents">
    <Type Name="ManagerEvent">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ManagerPost" Member="ManagerPosts">
    <Type Name="ManagerPost">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Participant" Member="Participants">
    <Type Name="Participant">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParticipantCommunity" Member="ParticipantCommunities">
    <Type Name="ParticipantCommunity">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommunityId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParticipantEvent" Member="ParticipantEvents">
    <Type Name="ParticipantEvent">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ParticipantPost" Member="ParticipantPosts">
    <Type Name="ParticipantPost">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Post" Member="Posts">
    <Type Name="Post">
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PostType" Member="PostTypes">
    <Type Name="PostType">
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SupportType" Member="SupportTypes">
    <Type Name="SupportType">
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UserEvent" Member="UserEvents">
    <Type Name="UserEvent">
      <Column Name="UserEventId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TypeEvent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Perform" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Moment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MoneyType" Member="MoneyTypes">
    <Type Name="MoneyType">
      <Column Name="MoneyTypeId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MoneyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ratio" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.htUsers" Member="htUsers">
    <Type Name="htUser">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.htUserFunction" Member="htUserFunctions">
    <Type Name="htUserFunction">
      <Column Name="UserFunctionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FunctionId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.htFunctions" Member="htFunctions">
    <Type Name="htFunction">
      <Column Name="FuntionId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FunctionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_CharityFund_Delete" Method="sp_CharityFund_Delete">
    <Parameter Name="FundId" Parameter="fundId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_CharityFund_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CommunityDonate_Delete" Method="sp_CommunityDonate_Delete">
    <Parameter Name="CommunityId" Parameter="communityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_CommunityDonate_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Donor_Delete" Method="sp_Donor_Delete">
    <Parameter Name="DonorId" Parameter="donorId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Donor_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Local_Insert" Method="sp_Local_Insert">
    <Parameter Name="LocalCode" Parameter="localCode" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LocalName" Parameter="localName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_Local_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Local_Load_List" Method="sp_Local_Load_List">
    <ElementType Name="sp_Local_Load_ListResult">
      <Column Name="LocalId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LocalCode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Manager_Delete" Method="sp_Manager_Delete">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Manager_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Event_Delete" Method="sp_Event_Delete">
    <Parameter Name="EventId" Parameter="eventId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Event_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Local_Delete" Method="sp_Local_Delete">
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Local_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Local_Update" Method="sp_Local_Update">
    <Parameter Name="LocalCode" Parameter="localCode" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LocalName" Parameter="localName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Local_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Manager_Insert" Method="sp_Manager_Insert">
    <Parameter Name="ManagerName" Parameter="managerName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Birth" Parameter="birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Manager_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Manager_Load_List" Method="sp_Manager_Load_List">
    <ElementType Name="sp_Manager_Load_ListResult">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Manager_Update" Method="sp_Manager_Update">
    <Parameter Name="ManagerName" Parameter="managerName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Birth" Parameter="birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Manager_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerCommunity_Delete" Method="sp_ManagerCommunity_Delete">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerCommunity_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerCommunity_Insert" Method="sp_ManagerCommunity_Insert">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CommunityId" Parameter="communityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerCommunity_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerCommunity_Load_List" Method="sp_ManagerCommunity_Load_List">
    <ElementType Name="sp_ManagerCommunity_Load_ListResult">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommunityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommunityName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerEvent_Delete" Method="sp_ManagerEvent_Delete">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerEvent_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerEvent_Insert" Method="sp_ManagerEvent_Insert">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventId" Parameter="eventId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerEvent_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerEvent_Load_List" Method="sp_ManagerEvent_Load_List">
    <ElementType Name="sp_ManagerEvent_Load_ListResult">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DesiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerPost_Insert" Method="sp_ManagerPost_Insert">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PostId" Parameter="postId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerPost_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerPost_Delete" Method="sp_ManagerPost_Delete">
    <Parameter Name="ManagerId" Parameter="managerId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ManagerPost_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ManagerPost_Load_List" Method="sp_ManagerPost_Load_List">
    <ElementType Name="sp_ManagerPost_Load_ListResult">
      <Column Name="ManagerId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ManagerName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Participant_Delete" Method="sp_Participant_Delete">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Participant_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Participant_Load_List" Method="sp_Participant_Load_List">
    <ElementType Name="sp_Participant_Load_ListResult">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Post_Delete" Method="sp_Post_Delete">
    <Parameter Name="PostId" Parameter="postId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Post_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PostType_Delete" Method="sp_PostType_Delete">
    <Parameter Name="PostTypeId" Parameter="postTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_PostType_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PostType_Insert" Method="sp_PostType_Insert">
    <Parameter Name="PostTypeName" Parameter="postTypeName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_PostType_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PostType_Load_List" Method="sp_PostType_Load_List">
    <ElementType Name="sp_PostType_Load_ListResult">
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_PostType_Update" Method="sp_PostType_Update">
    <Parameter Name="PostTypeName" Parameter="postTypeName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PostTypeId" Parameter="postTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_PostType_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserEvent_Insert" Method="sp_UserEvent_Insert">
    <Parameter Name="TypeEvent" Parameter="typeEvent" Type="System.Int32" DbType="Int" />
    <Parameter Name="Perform" Parameter="perform" Type="System.Int32" DbType="Int" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Moment" Parameter="moment" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="IPAddress" Parameter="iPAddress" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_UserEvent_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UserEvent_Load_List" Method="sp_UserEvent_Load_List">
    <ElementType Name="sp_UserEvent_Load_ListResult">
      <Column Name="UserEventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TypeEvent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Perform" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Moment" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SupportType_Update" Method="sp_SupportType_Update">
    <Parameter Name="SupportTypeName" Parameter="supportTypeName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SupportType_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SupportType_Insert" Method="sp_SupportType_Insert">
    <Parameter Name="SupportTypeName" Parameter="supportTypeName" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_SupportType_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SupportType_Delete" Method="sp_SupportType_Delete">
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_SupportType_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_SupportType_Load_List" Method="sp_SupportType_Load_List">
    <ElementType Name="sp_SupportType_Load_ListResult">
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MoneyType_Delete" Method="sp_MoneyType_Delete">
    <Parameter Name="MoneyTypeId" Parameter="moneyTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_MoneyType_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MoneyType_Insert" Method="sp_MoneyType_Insert">
    <Parameter Name="MoneyTypeName" Parameter="moneyTypeName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ratio" Parameter="ratio" Type="System.Double" DbType="Float" />
    <ElementType Name="sp_MoneyType_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MoneyType_Load_List" Method="sp_MoneyType_Load_List">
    <ElementType Name="sp_MoneyType_Load_ListResult">
      <Column Name="MoneyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoneyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ratio" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_MoneyType_Update" Method="sp_MoneyType_Update">
    <Parameter Name="MoneyTypeName" Parameter="moneyTypeName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ratio" Parameter="ratio" Type="System.Double" DbType="Float" />
    <Parameter Name="MoneyTypeId" Parameter="moneyTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_MoneyType_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantCommunity_Delete" Method="sp_ParticipantCommunity_Delete">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantCommunity_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantCommunity_Load_List" Method="sp_ParticipantCommunity_Load_List">
    <ElementType Name="sp_ParticipantCommunity_Load_ListResult">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CommunityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommunityName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoneyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoneyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ratio" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantEvent_Delete" Method="sp_ParticipantEvent_Delete">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantEvent_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantEvent_Load_List" Method="sp_ParticipantEvent_Load_List">
    <ElementType Name="sp_ParticipantEvent_Load_ListResult">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonateByParticipant" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="MoneyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoneyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ratio" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DesiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantPost_Delete" Method="sp_ParticipantPost_Delete">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantPost_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantPost_Load_List" Method="sp_ParticipantPost_Load_List">
    <ElementType Name="sp_ParticipantPost_Load_ListResult">
      <Column Name="ParticipantId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParticipantName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Money" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MoneyTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MoneyTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ratio" Type="System.Double" DbType="Float" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUsers_Login" Method="sp_htUsers_Login">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_htUsers_LoginResult">
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PassWord" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="UserCategory" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateStatus_Donor" Method="sp_UpdateStatus_Donor">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="DonorId" Parameter="donorId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UpdateStatus_DonorResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateStatus_Event" Method="sp_UpdateStatus_Event">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventId" Parameter="eventId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UpdateStatus_EventResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateStatus_Post" Method="sp_UpdateStatus_Post">
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="PostId" Parameter="postId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_UpdateStatus_PostResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Participant_Insert" Method="sp_Participant_Insert">
    <Parameter Name="ParticipantName" Parameter="participantName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DonateAmount" Parameter="donateAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Birth" Parameter="birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Participant_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Participant_Update" Method="sp_Participant_Update">
    <Parameter Name="ParticipantName" Parameter="participantName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="DonateAmount" Parameter="donateAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Birth" Parameter="birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Participant_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUsers_Delete" Method="sp_htUsers_Delete">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htUsers_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUsers_Insert" Method="sp_htUsers_Insert">
    <Parameter Name="UserName" Parameter="userName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="PassWord" Parameter="passWord" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="UserCategory" Parameter="userCategory" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htUsers_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUsers_Update" Method="sp_htUsers_Update">
    <Parameter Name="UserID" Parameter="userID" Type="System.Int32" DbType="Int" />
    <Parameter Name="FullName" Parameter="fullName" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Admin" Parameter="admin" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Active" Parameter="active" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="UserCategory" Parameter="userCategory" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htUsers_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htFunction_Load_User" Method="sp_htFunction_Load_User">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htFunction_Load_UserResult">
      <Column Name="FuntionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htFunctions_Delete" Method="sp_htFunctions_Delete">
    <Parameter Name="FunctionId" Parameter="functionId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htFunctions_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htFunctions_Insert" Method="sp_htFunctions_Insert">
    <Parameter Name="FunctionCode" Parameter="functionCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FunctionName" Parameter="functionName" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="sp_htFunctions_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htFunctions_Load_List" Method="sp_htFunctions_Load_List">
    <ElementType Name="sp_htFunctions_Load_ListResult">
      <Column Name="FuntionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FunctionCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FunctionName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htFunctions_Update" Method="sp_htFunctions_Update">
    <Parameter Name="FunctionCode" Parameter="functionCode" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="FunctionName" Parameter="functionName" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="FunctionId" Parameter="functionId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htFunctions_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUserFunction_Delete" Method="sp_htUserFunction_Delete">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htUserFunction_DeleteResult">
      <Column Name="Deleted" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_htUserFunction_Insert" Method="sp_htUserFunction_Insert">
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Parameter Name="FunctionId" Parameter="functionId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_htUserFunction_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CharityFund_Insert" Method="sp_CharityFund_Insert">
    <Parameter Name="FundName" Parameter="fundName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TotalAmount" Parameter="totalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_CharityFund_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CharityFund_Load_List" Method="sp_CharityFund_Load_List">
    <ElementType Name="sp_CharityFund_Load_ListResult">
      <Column Name="FundId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FundName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CharityFund_UPDATE" Method="sp_CharityFund_UPDATE">
    <Parameter Name="FundName" Parameter="fundName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="TotalAmount" Parameter="totalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FundId" Parameter="fundId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_CharityFund_UPDATEResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CommunityDonate_Insert" Method="sp_CommunityDonate_Insert">
    <Parameter Name="CommunityName" Parameter="communityName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToTalAmount" Parameter="toTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_CommunityDonate_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CommunityDonate_Load_List" Method="sp_CommunityDonate_Load_List">
    <ElementType Name="sp_CommunityDonate_Load_ListResult">
      <Column Name="CommunityId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CommunityName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_CommunityDonate_Update" Method="sp_CommunityDonate_Update">
    <Parameter Name="CommunityName" Parameter="communityName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Description" Parameter="description" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Url" Parameter="url" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="ToTalAmount" Parameter="toTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="CommunityId" Parameter="communityId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_CommunityDonate_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Donor_Insert" Method="sp_Donor_Insert">
    <Parameter Name="DonorName" Parameter="donorName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToTalAmount" Parameter="toTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_Donor_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Donor_Update" Method="sp_Donor_Update">
    <Parameter Name="DonorName" Parameter="donorName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Phone" Parameter="phone" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="ToTalAmount" Parameter="toTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="DonorId" Parameter="donorId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Donor_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Event_Insert" Method="sp_Event_Insert">
    <Parameter Name="EventName" Parameter="eventName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="DesiredAmount" Parameter="desiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="DonateAmount" Parameter="donateAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_Event_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Event_Load_List" Method="sp_Event_Load_List">
    <ElementType Name="sp_Event_Load_ListResult">
      <Column Name="EventId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FromDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ToDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DesiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="DonateAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Event_Update" Method="sp_Event_Update">
    <Parameter Name="EventName" Parameter="eventName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ToDate" Parameter="toDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="DesiredAmount" Parameter="desiredAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="DonateAmount" Parameter="donateAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="LocalId" Parameter="localId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventId" Parameter="eventId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_Event_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Post_Insert" Method="sp_Post_Insert">
    <Parameter Name="PostName" Parameter="postName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalAmount" Parameter="totalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PostTypeId" Parameter="postTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <ElementType Name="sp_Post_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Decimal" DbType="Decimal(38,0)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Post_Load_List" Method="sp_Post_Load_List">
    <ElementType Name="sp_Post_Load_ListResult">
      <Column Name="PostId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PostName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Slot" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PostTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PostTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Post_Update" Method="sp_Post_Update">
    <Parameter Name="PostName" Parameter="postName" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Parameter Name="Content" Parameter="content" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="Image" Parameter="image" Type="System.String" DbType="NVarChar(20)" />
    <Parameter Name="Status" Parameter="status" Type="System.Int32" DbType="Int" />
    <Parameter Name="TotalAmount" Parameter="totalAmount" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="SupportTypeId" Parameter="supportTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PostTypeId" Parameter="postTypeId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Title" Parameter="title" Type="System.String" DbType="NVarChar(MAX)" />
    <Parameter Name="PostId" Parameter="postId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Post_UpdateResult">
      <Column Name="Updated" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Donor_Load_List" Method="sp_Donor_Load_List">
    <ElementType Name="sp_Donor_Load_ListResult">
      <Column Name="DonorId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ToTalAmount" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SupportTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LocalId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonorName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SupportTypeName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LocalName" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_UpdateMoney_Participant" Method="sp_UpdateMoney_Participant">
    <Parameter Name="Money" Parameter="money" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_UpdateMoney_Category" Method="sp_UpdateMoney_Category">
    <Parameter Name="Category" Parameter="category" Type="System.Int32" DbType="Int" />
    <Parameter Name="Item" Parameter="item" Type="System.Int32" DbType="Int" />
    <Parameter Name="Money" Parameter="money" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="Slot" Parameter="slot" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_ParticipantCommunity_Insert" Method="sp_ParticipantCommunity_Insert">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <Parameter Name="CommunityId" Parameter="communityId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Money" Parameter="money" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="MoneyTypeId" Parameter="moneyTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantCommunity_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantEvent_Insert" Method="sp_ParticipantEvent_Insert">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <Parameter Name="EventId" Parameter="eventId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Money" Parameter="money" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="MoneyTypeId" Parameter="moneyTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantEvent_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_ParticipantPost_Insert" Method="sp_ParticipantPost_Insert">
    <Parameter Name="ParticipantId" Parameter="participantId" Type="System.Int32" DbType="Int" />
    <Parameter Name="PostId" Parameter="postId" Type="System.Int32" DbType="Int" />
    <Parameter Name="Money" Parameter="money" Type="System.Decimal" DbType="Decimal(18,0)" />
    <Parameter Name="MoneyTypeId" Parameter="moneyTypeId" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_ParticipantPost_InsertResult">
      <Column Name="[Identity]" Member="Identity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>